#!/usr/bin/env bash
# Записывает src/build_info.gd с текущим git commit SHA и timestamp'ом.
# Вызывается из Makefile (run/server/smoke/editor) и при docker-сборке прод-стека.
# Если .git недоступен (например, докер-контекст без .git), пишет sha="unknown",
# но это редкий случай — в обычном flow всё работает.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/src/build_info.gd"

if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    SHA="$(git -C "$REPO_ROOT" rev-parse --short=12 HEAD)"
    DIRTY=""
    if ! git -C "$REPO_ROOT" diff --quiet 2>/dev/null || ! git -C "$REPO_ROOT" diff --cached --quiet 2>/dev/null; then
        DIRTY="-dirty"
    fi
    SHA="${SHA}${DIRTY}"
else
    SHA="unknown"
fi

TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "$OUT" <<GD
extends Node
# AUTO-GENERATED by scripts/gen_build_info.sh — НЕ редактировать руками.
# Идентифицирует сборку клиента/сервера, сравнивается на handshake. Mismatch
# = клиент и сервер из разных коммитов (типичный случай — закешированный
# wasm/pck в браузере) → лобби показывает баннер с инструкцией обновиться.

const SHA: StringName = &"$SHA"
const BUILT_AT: String = "$TS"
GD

echo "[build-info] sha=$SHA built_at=$TS"
