extends Node
# AUTO-GENERATED by scripts/gen_build_info.sh — НЕ редактировать руками.
# Идентифицирует сборку клиента/сервера, сравнивается на handshake. Mismatch
# = клиент и сервер из разных коммитов (типичный случай — закешированный
# wasm/pck в браузере) → лобби показывает баннер с инструкцией обновиться.

const SHA: StringName = &"efafcad32e25-dirty"
const BUILT_AT: String = "2026-05-09T14:00:04Z"
