extends Node
# AUTO-GENERATED by scripts/gen_build_info.sh — НЕ редактировать руками.
# Идентифицирует сборку клиента/сервера, сравнивается на handshake. Mismatch
# = клиент и сервер из разных коммитов (типичный случай — закешированный
# wasm/pck в браузере) → лобби показывает баннер с инструкцией обновиться.

const SHA: StringName = &"09d1ded1a19e-dirty"
const BUILT_AT: String = "2026-05-09T13:04:57Z"
